name: CI/CD Pipeline for my app backend

on:
    push:
        branches: 
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name : Test hello
              run: echo "Hello"