name: CI/CD Pipeline for my app backend

on:
    push:
        branches: 
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name : Checkout Repo
              uses: actions/checkout@v2

            - name: Setup SSH Server
              uses: webfactory/ssh-agent@v0.5.3
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Deploy
              run: |
                ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << EOF
                    cd apps/backend
                    git pull
                    sudo docker compose build
                    sudo docker compose down
                    sudo docker compose up -d
                EOF
